<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cz.cdcargo</groupId>
        <artifactId>java-scaffold</artifactId>
        <version>1.0.0</version>
    </parent>

    <name>Java Scaffold Shell UI Webapp</name>
    <artifactId>java-scaffold-shell-ui-webapp</artifactId>
    <packaging>jar</packaging>

    <properties>   
        <helidon.version>4.4.1</helidon.version>
        <jte.version>3.2.3</jte.version>
        <flatlaf.version>3.7.1</flatlaf.version>
        <miglayout.version>11.4.3</miglayout.version>
        <tray.version>4.5</tray.version>
        <frontend.node.version>25.9.0</frontend.node.version>
        <slf4j.version>2.0.17</slf4j.version>
        <log4j.version>2.25.4</log4j.version>
        <junit.version>6.0.1</junit.version>
    </properties>

    <dependencyManagement>
        <dependencies>  
            <dependency>
                <groupId>io.helidon</groupId>
                <artifactId>helidon-bom</artifactId>
                <version>${helidon.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.helidon.webserver</groupId>
            <artifactId>helidon-webserver-http2</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.helidon.webserver</groupId>
            <artifactId>helidon-webserver-static-content</artifactId>
            <scope>compile</scope>
        </dependency>

       <dependency>
            <groupId>io.helidon.webserver</groupId>
            <artifactId>helidon-webserver-cors</artifactId>
            <scope>compile</scope>
        </dependency>        

        <dependency>
            <groupId>io.helidon.config</groupId>
            <artifactId>helidon-config-encryption</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.helidon.http.media</groupId>
            <artifactId>helidon-http-media-json</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.helidon.logging</groupId>
            <artifactId>helidon-logging-jul</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>gg.jte</groupId>
            <artifactId>jte</artifactId>
            <version>${jte.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>${flatlaf.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.miglayout</groupId>
            <artifactId>miglayout-swing</artifactId>
            <version>${miglayout.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.dorkbox</groupId>
            <artifactId>SystemTray</artifactId>
            <version>${tray.version}</version>
            <scope>compile</scope>
        </dependency>
        
        <dependency>
            <groupId>cz.cdcargo</groupId>
            <artifactId>java-scaffold-infra-db-duckdb</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>${slf4j.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-jul</artifactId>
            <version>${log4j.version}</version>
            <scope>compile</scope>
        </dependency>
        
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- core plugins -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>                
            </plugin>

            <!-- packaging plugins -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Automatic-Module-Name>cz.cdcargo.javascaffold.shell.ui.webapp</Automatic-Module-Name>
                            <Implementation-Title>${project.artifactId}</Implementation-Title>
                            <Implementation-Version>${project.version}</Implementation-Version>
                            <Implementation-Vendor>ČD Cargo, a.s.</Implementation-Vendor>
                            <Main-Class>cz.cdcargo.javascaffold.shell.ui.webapp.Main</Main-Class>                            
                            <Specification-Title>Java Scaffold</Specification-Title>
                            <Specification-Version>${project.version}</Specification-Version>                           
                            <Specification-Vendor>ČD Cargo, a.s.</Specification-Vendor>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

            <!-- tools plugins -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- other plugins -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>gg.jte</groupId>
                <artifactId>jte-maven-plugin</artifactId>
                <version>${jte.version}</version>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/main/jte</sourceDirectory>
                    <targetDirectory>${project.build.directory}/generated-sources/jte</targetDirectory>
                    <contentType>Html</contentType>
                </configuration>
                <executions>
                    <execution>
                        <?m2e execute onConfiguration,onIncremental?>
                        <id>generate</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <configuration>
                    <workingDirectory>${project.basedir}/src/main/frontend</workingDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v${frontend.node.version}</nodeVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm-install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm-build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                        <configuration>                            
                            <mainClass>cz.cdcargo.javascaffold.shell.ui.webapp.Main</mainClass>                            
                            <fallback>false</fallback>
                            <outputDirectory>${project.build.directory}/native-build</outputDirectory>                                  
                            <imageName>java-scaffold</imageName>
                            <buildArgs>                        
                                <buildArg>-Djava.awt.headless=false</buildArg>        
                                <buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
                                <buildArg>-H:CCompilerOption=-O3</buildArg>
                                <buildArg>-H:CCompilerOption=-mtune=native</buildArg>
                                <buildArg>-H:-CheckToolchain</buildArg>
                                <buildArg>-H:+AddAllCharsets</buildArg>
                                <buildArg>-Dfile.encoding=UTF-8</buildArg>
                                <buildArg>-Dstdout.encoding=UTF-8</buildArg>
                                <buildArg>-Dstderr.encoding=UTF-8</buildArg>
                                <buildArg>-H:IncludeLocales=en-US,cs-CZ</buildArg>                                                                
                                <buildArg>-R:MaxHeapSize=512m</buildArg>
                                <buildArg>--enable-native-access=ALL-UNNAMED</buildArg>
                                <buildArg>--future-defaults=all</buildArg> 
                                <buildArg>--initialize-at-run-time=com.formdev.flatlaf</buildArg>                                                
                            </buildArgs>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>gg.jte</groupId>
                        <artifactId>jte-maven-plugin</artifactId>
                        <version>${jte.version}</version>
                        <configuration>
                            <sourceDirectory>${project.basedir}/src/main/jte</sourceDirectory>
                            <targetDirectory>${project.build.directory}/classes</targetDirectory>
                            <contentType>Html</contentType>
                            <extensions>
                                <extension>
                                    <className>gg.jte.nativeimage.NativeResourcesExtension</className>
                                </extension>
                            </extensions>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>gg.jte</groupId>
                                <artifactId>jte-native-resources</artifactId>
                                <version>${jte.version}</version>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <?m2e execute onConfiguration,onIncremental?>
                                <id>precompile</id>
                                <phase>process-classes</phase>
                                <goals>
                                    <goal>precompile</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>java-agent</id>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>${exec.executable}</executable>
                                    <workingDirectory>${project.build.directory}</workingDirectory>
                                    <arguments>
                                        <argument>
                                            -agentlib:native-image-agent=config-merge-dir=${project.basedir}/src/main/resources/META-INF/native-image/${project.groupId}/${project.artifactId}
                                        </argument>
                                        <argument>-classpath</argument>
                                        <classpath />
                                        <argument>cz.cdcargo.javascaffold.shell.ui.webapp.Main</argument>
                                        <argument>--enable-native-access=ALL-UNNAMED</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>                  
                </plugins>
            </build>
        </profile>
    </profiles>
</project>